In [15]:
import pandas as pd

In [16]:
# Charger le fichier CSV dans un DataFrame

df = pd.read_csv('../../data/raw/stocks/stocks.csv')

# Exploration du dataframe

In [17]:
df.head(10)

                     company                       ticker    Layer
0               MP Materials                           MP  Layer 1
1             USA Rare Earth                         USAR  Layer 1
2          Lynas Rare Earths                    LYC (ASX)  Layer 1
3               Energy Fuels                         UUUU  Layer 1
4                  Albemarle                          ALB  Layer 1
5                        SQM                          SQM  Layer 1
6            Ganfeng Lithium  002460 (SZSE) / 1772 (HKEX)  Layer 1
7           Toray Industries                   3402 (TSE)  Layer 2
8                     Hexcel                          HXL  Layer 2
9  Mitsubishi Chemical Group                   4188 (TSE)  Layer 2

In [18]:
df["ticker"].unique()

<StringArray>
[                         'MP',                        'USAR',
                   'LYC (ASX)',                        'UUUU',
                         'ALB',                         'SQM',
 '002460 (SZSE) / 1772 (HKEX)',                  '3402 (TSE)',
                         'HXL',                  '4188 (TSE)',
 ...
                         'GXO',                 'DHL (XETRA)',
                         'WMT',             'TM / 7203 (TSE)',
                        'MELI',                         'PTC',
                         'NOW',                 'TMV (XETRA)',
                        'TRMB',                '018260 (KRX)']
Length: 107, dtype: str

I notice that some tickers will need cleaning:
- remove the stock exchange, when mentioned.
- only keep 1 ticker if there are multiple values.
- remove ticker that says "Private" as no data is available.
- Only keep the Layer number in the Layer column.

In [19]:
# Number of tickers not publicly traded
(df["ticker"] == "Private").sum()

np.int64(32)

In [20]:
df.describe()

             company   ticker    Layer
count            139      139      139
unique           139      107       18
top     MP Materials  Private  Layer 7
freq               1       32       18

In [21]:
df.shape

(139, 3)

In [22]:
# Types des colonnes
df.dtypes

company    str
ticker     str
Layer      str
dtype: object

In [23]:
# Valeurs nulles
df.isnull().sum()

company    0
ticker     0
Layer      0
dtype: int64