In [19]:
import pandas as pd

In [20]:
# Load the CSV file in a DataFrame.
df = pd.read_csv('../data/processed/stocks_cleaned.csv')
df

     ticker     layer
0        MP   Layer 1
1      USAR   Layer 1
2       LYC   Layer 1
3      UUUU   Layer 1
4       ALB   Layer 1
..      ...       ...
100     PTC  Layer 13
101     NOW  Layer 13
102     TMV  Layer 13
103    TRMB  Layer 13
104  018260  Layer 13

[105 rows x 2 columns]

# Transformation

Only keep the layer id in the Layer column.

In [21]:
df["layer_id"] = df["layer"].str.findall(r"(\d+)")
df = df.drop(["layer"], axis=1)
df.head(30)

    ticker   layer_id
0       MP        [1]
1     USAR        [1]
2      LYC        [1]
3     UUUU        [1]
4      ALB        [1]
5      SQM        [1]
6   002460        [1]
7     3402        [2]
8      HXL        [2]
9     4188        [2]
10     MMM        [2]
11      DD        [2]
12     BAS        [2]
13    1COV        [2]
14     EVK        [2]
15      MT        [2]
16    NVDA  [3, 4, 5]
17   GOOGL     [3, 4]
18    META        [3]
19  002230        [3]
20       U        [4]
21   GOOGL        [4]
22    QCOM        [5]
23     AMD        [5]
24    INTC        [5]
25    AMBA        [5]
26    LSCC        [5]
27    CEVA        [5]
28    NXPI        [5]
29     STM        [5]

Group the duplicate tickers.

In [22]:
df_grouped = df.groupby(["ticker"], as_index=False)[["layer_id"]].agg({"layer_id": "first"})
df_grouped

     ticker layer_id
0    000333     [11]
1    002050      [9]
2    002230      [3]
3    002460      [1]
4    002594      [6]
..      ...      ...
97     UUUU      [1]
98      VPG      [7]
99      WMT     [12]
100    WOLF      [6]
101    XPEV     [10]

[102 rows x 2 columns]

Check for any duplicates left.

In [23]:
df_grouped[df_grouped["ticker"].duplicated(keep=False)]

Empty DataFrame
Columns: [ticker, layer_id]
Index: []

# Export

In [24]:
df.to_csv('../data/processed/stocks_transformed.csv', index=False)