In [11]:
import pandas as pd

In [12]:
# Charger le fichier CSV dans un DataFrame

df = pd.read_csv('../data/raw/stocks.csv')

# Exploration du dataframe

In [13]:
df.head(10)

                     company                       ticker    Layer
0               MP Materials                           MP  Layer 1
1             USA Rare Earth                      Private  Layer 1
2          Lynas Rare Earths                    LYC (ASX)  Layer 1
3               Energy Fuels                         UUUU  Layer 1
4                  Albemarle                          ALB  Layer 1
5                        SQM                          SQM  Layer 1
6            Ganfeng Lithium  002460 (SZSE) / 1772 (HKEX)  Layer 1
7           Toray Industries                   3402 (TSE)  Layer 2
8                     Hexcel                          HXL  Layer 2
9  Mitsubishi Chemical Group                   4188 (TSE)  Layer 2

I notice that some tickers will need cleaning:
- remove the stock exchange.
- only keep 1 ticker if there is multiple values.

In [17]:
df.describe()

             company   ticker    Layer
count            139      139      139
unique           139      105       18
top     MP Materials  Private  Layer 7
freq               1       34       18

In [21]:
df.shape

(139, 3)