In [3]:
import pandas as pd

In [4]:
# Charger le fichier CSV dans un DataFrame

df = pd.read_csv('../data/raw/supply_chain_levels.csv')

# Exploration du dataframe

In [5]:
df.head(10)

,Supply Chain Level,Description,Companies
0,1. Upstream Mining & Raw Materials,Extraction and primary processing of essential...,"MP Materials, USA Rare Earth, Lynas Rare Earth..."
1,2. Material Refining & Advanced Structure,Chemical processing and advanced synthesis of ...,"Toray Industries, Hexcel, Mitsubishi Chemical ..."
2,3. Robot AI & Foundation Models,"Foundational physical artificial intelligence,...","NVIDIA, Google DeepMind, OpenAI, Physical Inte..."
3,"4. Simulation, Training & Robot OS","Physics-based digital twin environments, synth...","NVIDIA (Isaac), Google DeepMind (MuJoCo), Open..."
4,5. Compute & Edge AI Chips,"On-board processing silicon, edge AI accelerat...","NVIDIA, Qualcomm, AMD, Intel, Ambarella, Latti..."
5,"6. Power, Energy & Thermal Systems","High energy-density battery cells, intelligent...","CATL, LG Energy Solution, Samsung SDI, Panason..."
6,7. Sensors & Perception Systems,"Environmental spatial sensing arrays (LiDAR, s...","Sony, Samsung Electronics, Hesai Group, Ouster..."
7,"8. Actuators, Joints & Motion Control",Primary mechatronic movement stack consisting ...,"Harmonic Drive Systems, LeaderDrive, Nabtesco,..."
8,9. Actuator Assembly & Dexterous Hands,Subsystem contract assembly integrating motors...,"Sanhua Intelligent Controls, Tuopu Group, Zhao..."
9,10. Humanoid OEMs & System Builders,Prime Original Equipment Manufacturers that ar...,"Tesla (Optimus), Figure AI, Agility Robotics, ..."

In [6]:
df.describe()

,Supply Chain Level,Description,Companies
count,13,13,13
unique,13,13,13
top,1. Upstream Mining & Raw Materials,Extraction and primary processing of essential...,"MP Materials, USA Rare Earth, Lynas Rare Earth..."
freq,1,1,1

I will separate the Supply Chain Level number to the Supply Chain Level name.

In [7]:
df.shape

(13, 3)